#backend:
#  name: git-gateway
#  branch: main

# TESTING
backend:
  name: test-repo

local_backend: true

site_url: https://www.example.com
media_folder: static/assets
public_folder: /assets

collections:
  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: site/content/pages/home.md
        fields:
          - label: ID
            name: internal__id
            widget: hidden
            default: home
          - label: Hero Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Contact
        name: contact
        file: site/content/pages/contact-us.md
        fields:
          - label: ID
            name: internal__id
            widget: hidden
            default: contact
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: About
        name: about
        file: site/content/pages/about.md
        fields:
          - label: ID
            name: internal__id
            widget: hidden
            default: about
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Terms and Conditions
        name: terms-and-conditions
        file: site/content/pages/terms-and-conditions.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Privacy Policy
        name: privacy-policy
        file: site/content/pages/privacy-policy.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Body
            name: body
            widget: markdown
